package:
  name: pronto
  version: "2.4.4"

source:
  url: https://files.pythonhosted.org/packages/94/84/b37fbb501859a4891fa9367927dc3f7e7f9a416213545c34d7206966ae6b/pronto-2.4.4.tar.gz
  sha256: 17285b99ac374162aee29a6631cbb32e8b3969db55befa1bb2e01aedc8872e70

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - chardet >=3.0
    - fastobo >=0.9.0
    - networkx >=2.3
    - python-dateutil >=2.8
    - immutabledict

test:
  imports:
    - pronto
    - pronto.entity
    - pronto.logic
    - pronto.utils
    - pronto.parsers
    - pronto.serializers

about:
  home: http://github.com/althonos/pronto
  license: MIT
  summary: 'Python frontend to ontologies'
  license_family: MIT

extra:
  recipe-maintainers:
    - althonos
